[tool.cibuildwheel]
# Build wheels only for the platforms you need: x86_64 Linux and Apple Silicon Macs
build = ["cp38-*", "cp39-*", "cp310-*", "cp311-*", "cp312-*"]

# Skip problematic platforms only
skip = [
    "cp38-win*",  # Skip Python 3.8 on Windows
    "*-manylinux_i686",  # Skip 32-bit Linux builds
    "*-manylinux1_i686",  # Skip old 32-bit Linux builds
    "*-musllinux_i686",   # Skip 32-bit musl Linux builds
    "*-musllinux_x86_64", # Skip musl Linux (not needed)
    "*-manylinux1_x86_64", # Skip old manylinux1 (not needed)
    "*-win*",             # Skip all Windows builds
]

# Environment variables
[tool.cibuildwheel.environment]
# Ensure we have the right build environment and static linking
CIBW_BEFORE_BUILD_LINUX = "yum install -y ffmpeg cmake gcc-c++ || apt-get update && apt-get install -y ffmpeg cmake build-essential"
CIBW_BEFORE_BUILD_MACOS = "brew install ffmpeg cmake"
CIBW_BEFORE_BUILD_WINDOWS = ""

# Test command
CIBW_TEST_COMMAND = "python test_build.py"

# Build options - increase verbosity for better debugging
CIBW_BUILD_VERBOSITY = "2"

# Platform-specific settings
[tool.cibuildwheel.linux]
before-all = "yum install -y ffmpeg cmake gcc-c++ || apt-get update && apt-get install -y ffmpeg cmake build-essential"

[tool.cibuildwheel.macos]
before-all = "brew install ffmpeg cmake"

[tool.cibuildwheel.windows]
before-all = ""

# Ensure proper wheel building with static linking
[tool.cibuildwheel.build-options]
# Force static linking and proper RPATH settings
CIBW_CMAKE_OPTIONS = "-DWHISPER_BUILD_SHARED=OFF -DWHISPER_BUILD_TESTS=OFF -DWHISPER_BUILD_EXAMPLES=OFF" 