[tool.cibuildwheel]
# Build wheels only for the platforms you need: x86_64 Linux and Apple Silicon Macs
# Use explicit platform selection instead of exclusion
build = [
    # Linux x86_64 builds only
    "cp38-manylinux2014_x86_64",
    "cp39-manylinux2014_x86_64", 
    "cp310-manylinux2014_x86_64",
    "cp311-manylinux2014_x86_64",
    "cp312-manylinux2014_x86_64",
    "cp313-manylinux2014_x86_64",
    "cp314-manylinux2014_x86_64",
    "cp314t-manylinux2014_x86_64",
    # macOS Apple Silicon builds only
    "cp38-macosx_arm64",
    "cp39-macosx_arm64",
    "cp310-macosx_arm64", 
    "cp311-macosx_arm64",
    "cp312-macosx_arm64",
    "cp313-macosx_arm64",
    "cp314-macosx_arm64",
    "cp314t-macosx_arm64",
]

# Environment variables
[tool.cibuildwheel.environment]
# Ensure we have the right build environment and static linking
CIBW_BEFORE_BUILD_LINUX = "yum install -y ffmpeg cmake gcc-c++ || apt-get update && apt-get install -y ffmpeg cmake build-essential"
CIBW_BEFORE_BUILD_MACOS = "brew install ffmpeg cmake"
CIBW_BEFORE_BUILD_WINDOWS = ""

# Test command
CIBW_TEST_COMMAND = "python test_build.py"

# Build options - increase verbosity for better debugging
CIBW_BUILD_VERBOSITY = "2"

# Platform-specific settings
[tool.cibuildwheel.linux]
before-all = "yum install -y ffmpeg cmake gcc-c++ || apt-get update && apt-get install -y ffmpeg cmake build-essential"

[tool.cibuildwheel.macos]
before-all = "brew install ffmpeg cmake"

[tool.cibuildwheel.windows]
before-all = ""

# Ensure proper wheel building with static linking
[tool.cibuildwheel.build-options]
# Force static linking and proper RPATH settings
CIBW_CMAKE_OPTIONS = "-DWHISPER_BUILD_SHARED=OFF -DWHISPER_BUILD_TESTS=OFF -DWHISPER_BUILD_EXAMPLES=OFF" 